version: '3'

networks:
  api-connection:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    restart: always
    ports: 
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: web_server
    depends_on:
      - nest-api

  nest-api:
    container_name: api-server
    ports:
      - 3000:3000
    build:
      context: ./nest-api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
    volumes:
      - ./nest-api:/app
    
    
