version: '3'

networks:
  api-connection:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    restart: always
    ports: 
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: web_server
    networks:
      - api-connection
    depends_on:
      - nest-api

  nest-api:
    build:
      context: ./nest-api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
    volumes:
      - ./nest-api:/app
    networks:
      - api-connection
    
